name: Build Windows Portable ZIP
on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable long paths (Windows)
        shell: pwsh
        run: git config --global core.longpaths true

      - name: Setup Node LTS (no cache)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Show versions
        shell: pwsh
        run: |
          node -v
          npm -v

      - name: Install deps
        shell: pwsh
        run: npm install

      - name: Make ZIP only (verbose)
        shell: pwsh
        run: npx electron-forge make --targets=@electron-forge/maker-zip --platform=win32 --arch=x64 --verbose *>&1 | Tee-Object -FilePath build.log

      - name: Upload portable ZIP
        uses: actions/upload-artifact@v4
        with:
          name: ESPN_Fantasy_AI-Windows-Portable
          path: |
            out/make/zip/win32/x64/*.zip
            out/make/**/win32/x64/*.zip

      - name: Upload build log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: build.log
  
