name: Build Windows Installer

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install dependencies
      run: |
        npm install --save-dev electron electron-builder
        npm install
        
    - name: Build Windows App
      run: npx electron-builder --win --publish=never
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Upload Installer
      uses: actions/upload-artifact@v4
      with:
        name: ESPN_Fantasy_AI_Windows
        path: dist/*.exe
