name: Build Windows Portable ZIP
on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable long paths (Windows)
        run: git config --global core.longpaths true
        shell: pwsh

      - name: Setup Node LTS
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Versions
        run: |
          node -v
          npm -v
        shell: pwsh

      - name: Install deps
        run: |
          if (Test-Path package-lock.json) { npm ci } else { npm install }
        shell: pwsh

      - name: Make ZIP only (verbose)
        run: npx electron-forge make --targets=@electron-forge/maker-zip --platform=win32 --arch=x64 --verbose 2>&1 | tee build.log
        shell: bash

      - name: Upload portable ZIP
        uses: actions/upload-artifact@v4
        with:
          name: ESPN_Fantasy_AI-Windows-Portable
          path: |
            out/make/zip/win32/x64/*.zip
            out/make/**/win32/x64/*.zip

      - name: Upload build log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: build.log
